apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-nginx-configmap
data:
  default.conf: "server {\n  listen 8080;\n\n  location = /healthz {\n      access_log
    off;\n      default_type text/plain;\n      return 200 \"ok\\n\";\n  }\n  \n  location
    /api/v1/movies {\n    proxy_pass http://jenkins-movie-service-service:8000;\n
    \ }\n\n  location /api/v1/casts {\n    proxy_pass http://jenkins-cast-service-service:8000;\n
    \ }\n\n}"


