apiVersion: v1
kind: Secret

metadata:
  name: exam-cast-credentials-example

type: Opaque

stringData:
  cast-db-user: REPLACE_ME
  cast-db-password: REPLACE_ME
  cast-db-name: cast_db_dev
  cast-database-uri: REPLACE_ME