apiVersion: v1
kind: Secret

metadata:
  name: exam-movie-credentials-example

type: Opaque

stringData:
  movie-db-user: REPLACE_ME
  movie-db-password: REPLACE_ME
  movie-db-name: movie_db_dev
  movie-database-uri: REPLACE_ME