apiVersion: v1
kind: Service
metadata:
  name: cast-db-headless-service
  labels:
    app: jenkins-psql-cast-db

spec:
  clusterIP: None
  
  selector:
    app: jenkins-psql-cast-db
  
  ports:
    - name: postgres
      port: {{ .Values.castDatabase.service.port }}
      targetPort: {{ .Values.castDatabase.service.port }}
      protocol: TCP