apiVersion: v1
kind: Service
metadata:
  name: movie-db-headless-service
  labels:
    app: jenkins-psql-movie-db

spec:
  clusterIP: None
  
  selector:
    app: jenkins-psql-movie-db
  
  ports:
    - name: postgres
      port: {{ .Values.movieDatabase.service.port }}
      targetPort: {{ .Values.movieDatabase.service.targetPort }}
      protocol: TCP