apiVersion: v1
kind: Service

metadata:
  name: jenkins-psql-movie-db


spec:
  type: ClusterIP

  selector:
    app: jenkins-psql-movie-db
  
  ports:
    - name: postgres
      protocol: TCP
      port: {{ .Values.movieDatabase.service.port }}
      targetPort: {{ .Values.movieDatabase.service.targetPort }}